### ISSUE TITLE
Getting Runtime Error - TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by bahit** [anggaand123/Ionic-3-Material-Design#1]
Using the following specs:

```
cli packages: (/Users/bahit/.nvm/versions/node/v8.11.1/lib/node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : macOS Sierra

Misc:

    backend : pro
```
What I did:

1. Clone repo.
2. Ran `ionic serve` (in the background, it downloaded node_modules)
3. Get the following error stack:

```
TypeError: Object(...) is not a function
    at http://localhost:8100/build/vendor.js:41979:128
    at Object.exports.errorObject.e (http://localhost:8100/build/vendor.js:41981:2)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:26277:76)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:147271:81)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.__extends (http://localhost:8100/build/vendor.js:65358:89)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.177 (http://localhost:8100/build/main.js:468:76)
```

**Comment by whatnowangga** [comment]
try to npm install first before you run ionic serve

**Comment by bahit** [comment]
No dice. 

Ran new clone, tried `npm install` first then `ionic serve` still having the problem. 

Going to try it on a Windows 10 VM.

**Comment by bahit** [comment]
Tried on Windows 10 VM. Fresh install Node.js LTS 8.11.1, ionic and cordova. But still do not work.

Ran the following:

1. Clone Repo
2. `npm install`
3. `ionic serve`

Still getting error stack:

```
TypeError: Object(...) is not a function
    at http://localhost:8100/build/vendor.js:41979:128
    at Object.exports.errorObject.e (http://localhost:8100/build/vendor.js:41981:2)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:26277:76)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.<anonymous> (http://localhost:8100/build/vendor.js:147271:81)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.__extends (http://localhost:8100/build/vendor.js:65358:89)
    at __webpack_require__ (http://localhost:8100/build/vendor.js:55:30)
    at Object.179 (http://localhost:8100/build/main.js:800:76)
```

Below is my `ionic info`

```
$ ionic info

cli packages: (C:\Users\bahit\AppData\Roaming\npm\node_modules)

    @ionic/cli-utils  : 1.19.2
    ionic (Ionic CLI) : 3.20.0

local packages:

    @ionic/app-scripts : 3.1.8
    Ionic Framework    : ionic-angular 3.9.2

System:

    Node : v8.11.1
    npm  : 5.6.0
    OS   : Windows 10

Misc:

    backend : pro
```

**Comment by whatnowangga** [comment]
have you try npm rebuild node sass ??
